title: "Florin Dave's Portfolio!"
description: "Welcome to my Github portfolio! Here, I showcase my projects, skills, and learning journey in Information Systems."
show_downloads: true
theme: jekyll-theme-cayman
